

#ifndef MAMN14_ERRORS_UTILS_H
#define MAMN14_ERRORS_UTILS_H


#define ERR_CODE_LABEL_ALREADY_IN_USE 1
#define ERR_CODE_LABEL_IS_INSTRUCTION 2
#define  ERR_CODE_LABEL_IS_OPERATION 3
#define ERR_CODE_LABEL_IS_REGISTER 4

struct HashTable* get_errors_map();




#endif //MAMN14_ERRORS_UTILS_H
